&tao_start
		building_wall_file = '../../Bypass/building_wall.init'
		startup_file = '../../Bypass/bypass.tao'
/

&tao_design_lattice
		n_universes = 1
		design_lattice(1)%file = "vert_up_dog.bmad"
/

!-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
! CONSTRAINTS

&tao_d2_data
  d2_data%name = 'lat_corr'
  n_d1_data = 3
/

&tao_d1_data
  ix_d1_data = 1
  d1_data%name = 'dispersion'
  datum(1) =  'eta.b'     '' '' 'END'     'target'     0     1e1
  datum(2) = 'etap.b'	 '' '' 'END'	  'target'     0     1e1
/

&tao_d1_data
  ix_d1_data = 2
  d1_data%name = 'beta'
  datum(1) =  'beta.b'     '' 'BEGINNING' 'END'     'max'     40     1e1
  datum(2) =  'beta.a'	   '' 'BEGINNING' 'END'	  'max'	  40     1e1
/

&tao_d1_data
  ix_d1_data = 3
  d1_data%name = 'beta'
  datum(1) =  'alpha.b'    '' '' 'END'   'min'     -2     1e1
  datum(2) =  'alpha.a'	   '' '' 'END'	  'min'	 -7     1e1
/

! &tao_d1_data
  ! ix_d1_data = 4
  ! d1_data%name = 'beta'
  ! datum(1) =  'eta.a'       '' '' 'END'   'target'     0     1e2
  ! datum(2) =  'etap.a'	   '' '' 'END'	  'target'	 0     1e2
! /

!----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
! VARIABLES

&tao_var
	v1_var%name = 'MatchyMcMatchFace1'
	search_for_lat_eles = 'MatchyMcMatchFace1'
	default_step = 1e-4
	default_attribute = 'b1_gradient'
	default_merit_type = 'limit'
	default_low_lim = -15
	default_high_lim = 15
	default_weight = 1
  ix_min_var = 1
  default_key_delta = 1e-2
  default_key_bound = T
/

&tao_var
	v1_var%name = 'MatchyMcMatchFace2'
	search_for_lat_eles = 'MatchyMcMatchFace2'
	default_step = 1e-4
	default_attribute = 'b1_gradient'
	default_merit_type = 'limit'
	default_low_lim = -15
	default_high_lim = 15
	default_weight = 1
  ix_min_var = 1
  default_key_delta = 1e-2
  default_key_bound = T
/

&tao_var
	v1_var%name = 'MVUQUA01'
	search_for_lat_eles = 'MVUQUA01'
	default_step = 1e-4
	default_attribute = 'b1_gradient'
	default_merit_type = 'limit'
	default_low_lim = -15
	default_high_lim = 15
	default_weight = 1
  ix_min_var = 1
  default_key_delta = 1e-2
  default_key_bound = T
/

&tao_var
	v1_var%name = 'MVUQUA02'
	search_for_lat_eles = 'MVUQUA02'
	default_step = 1e-4
	default_attribute = 'b1_gradient'
	default_merit_type = 'limit'
	default_low_lim = -15
	default_high_lim = 15
	default_weight = 1
  ix_min_var = 1
  default_key_delta = 1e-2
  default_key_bound = T
/

&tao_var
	v1_var%name = 'MVUQUA03'
	search_for_lat_eles = 'MVUQUA03'
	default_step = 1e-4
	default_attribute = 'b1_gradient'
	default_merit_type = 'limit'
	default_low_lim = -15
	default_high_lim = 15
	default_weight = 1
  ix_min_var = 1
  default_key_delta = 1e-2
  default_key_bound = T
/